# see http://tracker.ceph.com/issues/20360 and http://tracker.ceph.com/issues/18126
os_type: centos

tasks:
- install:
- ceph: {cluster: c1}
- ceph: {cluster: c2}
- rgw:
    c1.client.0:
      valgrind: [--tool=memcheck, --max-threads=1024] # http://tracker.ceph.com/issues/25214
    c1.client.1:
      valgrind: [--tool=memcheck, --max-threads=1024]
    c2.client.0:
      valgrind: [--tool=memcheck, --max-threads=1024]
    c2.client.1:
      valgrind: [--tool=memcheck, --max-threads=1024]
- rgw-multisite:
- rgw-multisite-tests:
    config:
      reconfigure_delay: 60
