tasks:
- install:
    extra_system_packages:
      deb: ['bison', 'flex', 'libelf-dev', 'libssl-dev']
      rpm: ['bison', 'flex', 'elfutils-libelf-devel', 'openssl-devel']
- ceph:
- thrashosds:
    chance_down: 1.0
    powercycle: true
    timeout: 600
