tasks:
- install: null
- ceph:
    fs: ext4
    log-whitelist:
    - overall HEALTH_
    - \(OSDMAP_FLAGS\)
    - \(OSD_
    - \(PG_
    - \(POOL_
    - \(CACHE_POOL_
    - \(SMALLER_PGP_NUM\)
    - \(OBJECT_
    - \(REQUEST_SLOW\)
    - \(TOO_FEW_PGS\)
    - reached quota
    - but it is still running
    - objects unfound and apparently lost
    - \(POOL_APP_NOT_ENABLED\)
- thrashosds:
    chance_pgnum_grow: 2
    chance_pgpnum_fix: 1
    timeout: 1200
- workunit:
    clients:
      client.0:
      - rados/test.sh
