tasks:
- install:
- ceph:
    log-whitelist:
      - overall HEALTH_
      - \(OSDMAP_FLAGS\)
      - \(OSD_
      - \(PG_
      - \(POOL_
      - \(CACHE_POOL_
    fs: xfs
- ceph-fuse:
- workunit:
    clients:
      client.0:
        - rbd/test_librbd.sh
    env:
      RBD_FEATURES: "1"
