tasks:
- check-counter:
    counters:
      mds:
        - "mds.dir_split"
- workunit:
    clients:
      all:
        - fs/norstats

overrides:
  ceph:
    conf:
      client:
        client dirsize rbytes: false
